# https://www.netlifycms.org/docs/add-to-your-site/#configuration

backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "img"

collections:
- label: "Page"
  name: "page"
  folder: "pages/"
  create: true
  identifier_field: title
  extension: html
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Permalink", name: "permalink", widget: "string"}
    - {label: "Layout", name: "layout", widget: "select", options: ["default"]}
    - {label: "Body", name: "body", widget: "text"}

